# Generated by Django 5.0.1 on 2024-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=60)),
                ('title', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=60)),
                ('article_content', models.CharField(default='', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
