# Generated by Django 5.0.1 on 2024-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
