# Generated by Django 5.0.1 on 2024-01-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_footballteam_playerstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballplayer',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='logo_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='official_website_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
