# Generated by Django 5.0.1 on 2024-02-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_footballplayer_photo_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
