# Generated by Django 5.0.1 on 2024-03-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryReportArticle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=60)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=60)),
                ('article_content', models.CharField(default='', max_length=5000)),
                ('image_url', models.CharField(default='', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
