# Generated by Django 5.0.1 on 2024-03-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_injuryreportarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballteam',
            name='abbreviation',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='conference',
            field=models.CharField(choices=[('AFC', 'American Football Conference'), ('NFC', 'National Football Conference')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='division',
            field=models.CharField(choices=[('AFC North', 'AFC North'), ('AFC South', 'AFC South'), ('AFC East', 'AFC East'), ('AFC West', 'AFC West'), ('NFC North', 'NFC North'), ('NFC South', 'NFC South'), ('NFC East', 'NFC East'), ('NFC West', 'NFC West')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='instagram_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='last_season_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='last_season_ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='last_season_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='team_color_primary',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='team_color_secondary',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='this_season_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='this_season_ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='this_season_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='twitter_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
