# Generated by Django 5.0.1 on 2024-03-07 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_footballteam_abbreviation_footballteam_conference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('season_passing_yards', models.IntegerField()),
                ('season_passing_tds', models.IntegerField()),
                ('season_passer_rating', models.FloatField()),
                ('season_ints', models.IntegerField()),
                ('season_fumbles', models.IntegerField()),
                ('season_fumbles_lost', models.IntegerField()),
                ('season_safeties', models.IntegerField()),
                ('season_rushing_yards', models.IntegerField()),
                ('season_rushing_tds', models.IntegerField()),
                ('season_receptions', models.IntegerField()),
                ('season_receiving_yards', models.IntegerField()),
                ('season_receiving_tds', models.IntegerField()),
                ('season_fgm', models.IntegerField()),
                ('season_fga', models.IntegerField()),
                ('season_xpm', models.IntegerField()),
                ('season_xpa', models.IntegerField()),
                ('season_fantasy_points', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='api.footballplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_team', to='api.footballteam')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
