# Generated by Django 5.0.1 on 2024-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_injuryreportarticle_player_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='fgm',
            new_name='fgm0_19',
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='fgm20_39',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='fgm40_49',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='fgm50_plus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
