# Generated by Django 5.0.1 on 2024-03-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_fgm_playerseasonstats_fgm0_19_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=10)),
                ('week', models.IntegerField()),
                ('home', models.BooleanField()),
                ('passing_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('passer_rating', models.FloatField()),
                ('ints', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('fumbles_lost', models.IntegerField()),
                ('safeties', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('rushing_tds', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('fgm0_19', models.IntegerField()),
                ('fgm20_39', models.IntegerField()),
                ('fgm40_49', models.IntegerField()),
                ('fgm50_plus', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('xpm', models.IntegerField()),
                ('xpa', models.IntegerField()),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_opponent', to='api.footballteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_log', to='api.footballplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team', to='api.footballteam')),
            ],
        ),
    ]
