# Generated by Django 5.0.3 on 2024-03-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_playergamelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryreportarticle',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='injuryreportarticle',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
