# Generated by Django 5.0.3 on 2025-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_fantasydraft_fantasydraftteam_fantasydraftselection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasydraft',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fantasydraftselection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fantasydraftteam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
