# Generated by Django 5.0.3 on 2025-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_fantasydraft_id_alter_fantasydraftselection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasydraft',
            name='current_pick',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
